# Ejercicios Tema 5: Business Intelligence

In [52]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/app/my_data/students_diplomado_data_science_fmat/class_of_2024/Natasha_Baeza/gapminder_data_world_health.csv')

### Ejercicio 2

Desarrolla una gráfica de barras en Looker Studio que represente la analítica descriptiva del KPI de esperanza de vida promedio.
- Prueba mostrando 5 países pobres (tu decides el subset apropiado) una esperanza de vida baja en el año más reciente disponible.
- NOTA: En Looker Studio las variables categóricas se les llama "Dimension" y a las numericas se les llama "Metric"
- Publica la grafica de barras e incrustala en este notebook usando IPython.display checa ejemplo aquí

In [30]:
#Se realiza el campo calculado con la métrica de promedio de esperanza de vida
# Se utiliza doble filtro: el primero filtrando por el año 2007 y el segundo filtrando para que se muestren
# los 5 paises con esperanza de vida más baja en ese año (observando se usa el filtro que sea menor o igual a 42.6)

In [36]:
import IPython
src= 'https://lookerstudio.google.com/embed/reporting/36e6c2fe-550d-402a-acb2-75b63aabb7ed/page/v0kCE'
IPython.display.IFrame(src,width=650, height=300)

De lo anterior se observa que Suazilandia es el que tiene la esperanza de vida promedio más baja seguido por Mozambique, de igual forma Sierra y Lesotho son los que tienen una esperanza de vida similar

### Ejercicio 3

Desarrolla un gráfico de dispersión que represente la analítica diagnóstica, examinando la relación entre el PIB per cápita y la esperanza de vida de esos países pobres.
- Prueba correlacionando ambas variables, checa que pasa comparando años
- Publica la grafica de barras e incrustala en este notebook usando IPython.display checa ejemplo aquí

In [35]:
src= 'https://lookerstudio.google.com/embed/reporting/36e6c2fe-550d-402a-acb2-75b63aabb7ed/page/v0kCE'
IPython.display.IFrame(src,width=650, height=300)

Se realizan comparaciones respecto a lo más reciente con lo anterior y se puede observar que en 2007 Swaziland tiene la esperanza menor de todos lo países (como se aprecia en el ejercicio anterior), sin embargo su PIB es el más alto de todos los del gráfico, adicional a esto se ve que tuvo una caida en la esperanza de vida respecto al año 2022

Zambia y Sierra tuvieron un aumento en su esperanza de vida comparado vs 2022 pero su PIB sigue aproximadamente similar en ambos años

### Ejercicio 4

- Desarrolla un gráfico linear o waterfall que represente la analítica predictiva mostrando la tendencia de la esperanza de vida en los países seleccionados en los próximos años.
- Que patrones puedes observar? Apoyate agregando un filtro

Se filtra el dataset por los países de interés que se obtuvieron en los ejercicios anteriores como los países de espernza de vida más baja:
- Swaziland
- Zambia
- Mozambique
- Lesotho
- Sierra Leone

In [85]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [53]:
dataset

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [54]:
paises= ['Swaziland', 'Zambia', 'Mozambique','Lesotho','Sierra Leone']

In [55]:
df = dataset[dataset['country'].isin(paises)]

In [56]:
df = df[['country', 'year','lifeExp']]

In [91]:
## Se filtra por cada país para calcular la predicción para los siguientes años
dfLes=df[df['country'] == 'Lesotho']
dfMozam=df[df['country'] == 'Mozambique']
dfSL=df[df['country'] == 'Sierra Leone']
dfSwa=df[df['country'] == 'Swaziland']
dfZam=df[df['country'] == 'Zambia']

In [93]:
###Calculo de predicciones para Lesotho
X1 = dfLes[['year']]
y1 = dfLes['lifeExp']
model = LinearRegression()
model.fit(X1, y1)
future_years = np.array([[2012], [2017], [2022], [2027]])
predictions = model.predict(future_years)
predictions

/opt/venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53.1129697 , 53.59079837, 54.06862704, 54.54645571])

In [94]:
###Calculo de predicciones para Mozambique
X2 = dfMozam[['year']]
y2 = dfMozam['lifeExp']
model = LinearRegression()
model.fit(X2, y2)
future_years = np.array([[2012], [2017], [2022], [2027]])
predictions = model.predict(future_years)
predictions

/opt/venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47.67527273, 48.7976993 , 49.92012587, 51.04255245])

In [96]:
###Calculo de predicciones para Sierra Leone
X3 = dfSL[['year']]
y3 = dfSL['lifeExp']
model = LinearRegression()
model.fit(X3, y3)
future_years = np.array([[2012], [2017], [2022], [2027]])
predictions = model.predict(future_years)
predictions

/opt/venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([43.72530303, 44.79547786, 45.86565268, 46.93582751])

In [98]:
###Calculo de predicciones para Swaziland
X4 = dfSwa[['year']]
y4 = dfSwa['lifeExp']
model = LinearRegression()
model.fit(X4, y4)
future_years = np.array([[2012], [2017], [2022], [2027]])
predictions = model.predict(future_years)
predictions

/opt/venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52.09234848, 52.56772261, 53.04309674, 53.51847086])

In [99]:
###Calculo de predicciones para Zambia
X5 = dfZam[['year']]
y5 = dfZam['lifeExp']
model = LinearRegression()
model.fit(X5, y5)
future_years = np.array([[2012], [2017], [2022], [2027]])
predictions = model.predict(future_years)
predictions

/opt/venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([44.03251515, 43.73038928, 43.4282634 , 43.12613753])

Posterior a los datos anteriores, se agregan a un dataset para crear el gráfico en looker studio

In [100]:
src= 'https://lookerstudio.google.com/embed/reporting/36e6c2fe-550d-402a-acb2-75b63aabb7ed/page/v0kCE'
IPython.display.IFrame(src,width=650, height=300)

Se observa en los datos que hasta los datos que se tienen en el dataset se aprecia que hay una subia sin embargo entre 2007 y 2012 hay una baja para luego mantener similar a partir de 2012 con la predicción, para los países de Zambia, Sierra  si se tiene un aumento y en el caso de Lesotho se predice un ligero decremento en la esperanza de vida

### Ejercicio 5

- Para la analítica prescriptiva normalmente un diagrama de Sankey puede ayudar a la toma de decisones futuras. Con los datos que tenemos no es posible haver uno.
- Investiga sobre los diagrama de Sankey y explica que tipo de datos necesitariamos para graficar, asumiendo que quisieramos recomendar intervenciones a estos países para incrementar su esperanza de vida.

El diagrama de Sankey funciona para poder visualizar relaciones y patrones de los datos, si quisieramos dar recomendaciontes necesitarìamos tener datos relacionados con:
- Datos financieros (Ingresos de los países)
- Salud (Programas realizados, enfermedades)
- Nutrición
- Acciones históricas (resultados)
Con esto se podría tener como ha influido lo que se está trabajando o se ha trabajado y donde se pueden enfocar acciones